import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { House, Images } from 'lucide-react';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const jetbrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigationItems = [
    { name: 'Home', href: '#', icon: House },
    { name: 'Showcase', href: '#', icon: Images },
  ];

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased min-h-screen flex flex-col relative`}
      >
        <section className="fixed top-2 left-0 w-full flex justify-center z-50">
          <nav>
            <ul className="flex flex-row gap-2 rounded-full bg-background/80 px-3 shadow-lg backdrop-blur">
              {navigationItems.map((item) => (
                <li
                  key={item.name}
                  className="flex items-center"
                >
                  <button className="px-2 py-1 rounded-full hover:bg-foreground/10 text-sm">
                    <item.icon />
                  </button>
                </li>
              ))}
            </ul>
          </nav>
        </section>
        <main className="flex-1 flex">{children}</main>
      </body>
    </html>
  );
}

